spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://game-pms
          predicates:
            - Path=/api/gamewebpms/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: thirdParty_route
          uri: lb://game-thiryParty
          predicates:
            - Path=/api/thirdParty/**
          filters:
            - RewritePath=/api/thirdParty/(?<segment>.*),/$\{segment}


        - id: ums_route
          uri: lb://game-ums
          predicates:
            - Path=/api/gamewebums/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}


        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: product_gameweb_route
          uri: lb://game-pms
          predicates:
            - Host=gameweb.com


        - id: auth_gameweb_route
          uri: lb://game-auth
          predicates:
            - Host=auth.gameweb.com

